steps:
  - name: Set up Python
    uses: actions/setup-python@v3
    with:
      python-version: '3.11'

  - name: Set PYTHONPATH to include src
    run: |
      echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

  - name: Install dependencies
    run: pip install -r requirements.txt

  - name: Run tests
    run: pytest src/test
